"""agregar_campo_can_bulk_delete_emails

Revision ID: 0a828cc927f4
Revises: 0f6d63d88a73
Create Date: 2026-01-06 15:49:06.757809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a828cc927f4'
down_revision = '0f6d63d88a73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_bulk_delete_emails', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_bulk_delete_emails')

    # ### end Alembic commands ###
