"""cambiar_processing_time_a_intervalo_y_agregar_activated_at

Revision ID: 29b4f76f7dff
Revises: bb6bd174a633
Create Date: 2025-12-07 20:24:01.390194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b4f76f7dff'
down_revision = 'bb6bd174a633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite requiere batch_alter_table para cambiar columnas
    from alembic import context
    from sqlalchemy import inspect
    
    # Verificar si la columna activated_at ya existe
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('drive_transfers')]
    column_exists = 'activated_at' in columns
    
    with op.batch_alter_table('drive_transfers', schema=None) as batch_op:
        # Agregar columna activated_at (nullable) solo si no existe
        if not column_exists:
            batch_op.add_column(sa.Column('activated_at', sa.DateTime(), nullable=True))
        
        # Cambiar processing_time de Time a String
        # Primero crear una columna temporal
        batch_op.add_column(sa.Column('processing_time_new', sa.String(length=20), nullable=True))
    
    # Convertir valores existentes de Time a String (formato "HH:MM")
    # Para registros existentes, convertir la hora a formato de intervalo por defecto (24h)
    op.execute("""
        UPDATE drive_transfers 
        SET processing_time_new = '24H' 
        WHERE processing_time_new IS NULL
    """)
    
    # Eliminar la columna antigua y renombrar la nueva
    with op.batch_alter_table('drive_transfers', schema=None) as batch_op:
        batch_op.drop_column('processing_time')
        batch_op.alter_column('processing_time_new', new_column_name='processing_time', nullable=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revertir cambios
    with op.batch_alter_table('drive_transfers', schema=None) as batch_op:
        # Cambiar processing_time de String a Time
        batch_op.add_column(sa.Column('processing_time_old', sa.Time(), nullable=True))
    
    # Convertir valores de String a Time (asumiendo formato "HH:MM" o "24H" como 00:00)
    op.execute("""
        UPDATE drive_transfers 
        SET processing_time_old = time('00:00:00')
        WHERE processing_time_old IS NULL
    """)
    
    with op.batch_alter_table('drive_transfers', schema=None) as batch_op:
        batch_op.drop_column('processing_time')
        batch_op.alter_column('processing_time_old', new_column_name='processing_time', nullable=False)
        batch_op.drop_column('activated_at')
    
    # ### end Alembic commands ###
