"""add can_use_coupons field to users

Revision ID: 3f1f065afd4d
Revises: 9a8b7c6d5e4f
Create Date: 2026-01-08 17:06:08.024125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1f065afd4d'
down_revision = '9a8b7c6d5e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_use_coupons', sa.Boolean(), nullable=False, server_default='0'))
    
    # Asegurar que todos los usuarios existentes tengan can_use_coupons = False
    op.execute("UPDATE users SET can_use_coupons = 0 WHERE can_use_coupons IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_use_coupons')

    # ### end Alembic commands ###
