"""Agregar tablas SMS

Revision ID: 5a3ee0cc817f
Revises: g2h3i4j5k6l7
Create Date: 2025-11-26 22:32:06.943619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '5a3ee0cc817f'
down_revision = 'g2h3i4j5k6l7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('twilio_account_sid', sa.String(length=255), nullable=False),
    sa.Column('twilio_auth_token', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('sms_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_configs_is_enabled'), ['is_enabled'], unique=False)

    op.create_table('sms_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sms_config_id', sa.Integer(), nullable=False),
    sa.Column('from_number', sa.String(length=20), nullable=False),
    sa.Column('to_number', sa.String(length=20), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('twilio_message_sid', sa.String(length=255), nullable=True),
    sa.Column('twilio_status', sa.String(length=50), nullable=True),
    sa.Column('raw_data', sqlite.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sms_config_id'], ['sms_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twilio_message_sid')
    )
    with op.batch_alter_table('sms_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_messages_from_number'), ['from_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_messages_processed'), ['processed'], unique=False)
        batch_op.create_index(batch_op.f('ix_sms_messages_sms_config_id'), ['sms_config_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_messages_sms_config_id'))
        batch_op.drop_index(batch_op.f('ix_sms_messages_processed'))
        batch_op.drop_index(batch_op.f('ix_sms_messages_from_number'))
        batch_op.drop_index(batch_op.f('ix_sms_messages_created_at'))

    op.drop_table('sms_messages')
    with op.batch_alter_table('sms_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_configs_is_enabled'))

    op.drop_table('sms_configs')
    # ### end Alembic commands ###
