"""Cambiar campo numero de String a Text en ServiceModel

Revision ID: 603951adec63
Revises: 88153dddea38
Create Date: 2025-11-27 18:21:18.655757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603951adec63'
down_revision = '88153dddea38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowed_sms_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowed_sms_numbers_phone_number'))
        batch_op.create_index('ix_allowed_sms_numbers_phone_number', ['phone_number'], unique=False)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('allowed_sms_numbers', schema=None) as batch_op:
        batch_op.drop_index('ix_allowed_sms_numbers_phone_number')
        batch_op.create_index(batch_op.f('ix_allowed_sms_numbers_phone_number'), ['phone_number'], unique=1)

    # ### end Alembic commands ###
