"""Aumentar tamaño de phone_number para soportar correos electrónicos

Revision ID: 6578b75663e6
Revises: 85fb681d6ade
Create Date: 2025-11-28 00:21:08.483242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6578b75663e6'
down_revision = '85fb681d6ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowed_sms_numbers', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_allowed_sms_numbers_phone_number'))
        batch_op.create_index(batch_op.f('ix_allowed_sms_numbers_phone_number'), ['phone_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowed_sms_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowed_sms_numbers_phone_number'))
        batch_op.create_index(batch_op.f('ix_allowed_sms_numbers_phone_number'), ['phone_number'], unique=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
