"""agregar_campo_can_manage_2fa_emails

Revision ID: 7804b37b6572
Revises: 1b2c3d4e5f6a
Create Date: 2026-01-06 17:38:11.677438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7804b37b6572'
down_revision = '1b2c3d4e5f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_manage_2fa_emails', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_manage_2fa_emails')

    # ### end Alembic commands ###
