"""Eliminar columna numero de services

Revision ID: 85fb681d6ade
Revises: 603951adec63
Create Date: 2025-11-27 18:39:42.569350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85fb681d6ade'
down_revision = '603951adec63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('numero')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
