"""Agregar campo numero a servicios

Revision ID: 88153dddea38
Revises: a0e6c8b16c6a
Create Date: 2025-11-27 18:10:19.363330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88153dddea38'
down_revision = 'a0e6c8b16c6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('numero')

    # ### end Alembic commands ###
