"""Crear tablas iniciales

Revision ID: 8be184b55cc2
Revises: 
Create Date: 2025-09-24 19:15:28.882538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '8be184b55cc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('api_type', sa.String(length=50), nullable=True),
    sa.Column('api_url', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('drive_subtitle_photos', sa.String(length=100), nullable=True),
    sa.Column('drive_subtitle_videos', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_name', sa.String(length=50), nullable=False),
    sa.Column('key_value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_name')
    )
    op.create_table('blocked_senders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('sender_domain', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocked_senders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocked_senders_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocked_senders_sender_domain'), ['sender_domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocked_senders_sender_email'), ['sender_email'], unique=False)

    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('drive_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credentials_json', sa.Text(), nullable=False),
    sa.Column('drive_original_id', sa.String(length=128), nullable=False),
    sa.Column('drive_processed_id', sa.String(length=128), nullable=False),
    sa.Column('drive_deleted_id', sa.String(length=128), nullable=True),
    sa.Column('processing_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_processed', sa.DateTime(), nullable=True),
    sa.Column('consecutive_errors', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_buzon_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('max_emails_per_second', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('email_tags_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('filter_from_email', sa.Text(), nullable=True),
    sa.Column('filter_to_email', sa.Text(), nullable=True),
    sa.Column('filter_subject_contains', sa.Text(), nullable=True),
    sa.Column('filter_content_contains', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=200), nullable=True),
    sa.Column('keyword', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('cut_after_html', sa.String(length=255), nullable=True),
    sa.Column('cut_before_html', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gsheets_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantilla', sa.String(length=64), nullable=False),
    sa.Column('credentials_json', sa.Text(), nullable=False),
    sa.Column('sheet_id', sa.String(length=128), nullable=False),
    sa.Column('tab_name', sa.String(length=128), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gsheets_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gsheets_links_plantilla'), ['plantilla'], unique=False)

    op.create_table('html_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imap_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=200), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password_enc', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('folders', sa.String(length=500), server_default='INBOX', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observer_imap_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=200), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password_enc', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('folders', sa.String(length=500), server_default='INBOX', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host', 'port', 'username', name='uq_observer_host_port_user')
    )
    op.create_table('regexes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=200), nullable=True),
    sa.Column('pattern', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('border_color', sa.String(length=50), nullable=True),
    sa.Column('gradient_color', sa.String(length=50), nullable=True),
    sa.Column('click_color1', sa.String(length=50), nullable=True),
    sa.Column('click_color2', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.Column('visibility_mode', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('store_coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('discount_cop', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('max_uses_per_user', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('show_public', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('store_coupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_coupons_enabled'), ['enabled'], unique=False)

    op.create_table('store_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price_cop', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('is_preset', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('store_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_products_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_products_is_preset'), ['is_preset'], unique=False)

    op.create_table('store_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('descuentos', sqlite.JSON(), nullable=True),
    sa.Column('tipo_precio', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('store_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_roles_enabled'), ['enabled'], unique=False)

    op.create_table('store_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('store_tool_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('store_tool_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_tool_info_enabled'), ['enabled'], unique=False)

    op.create_table('store_youtube_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('twofa_enabled', sa.Boolean(), nullable=True),
    sa.Column('twofa_method', sa.String(length=10), nullable=True),
    sa.Column('twofa_secret_enc', sa.String(length=255), nullable=True),
    sa.Column('pending_2fa_method', sa.String(length=10), nullable=True),
    sa.Column('pending_2fa_code', sa.String(length=10), nullable=True),
    sa.Column('pending_2fa_code_expires', sa.DateTime(), nullable=True),
    sa.Column('pending_email_code', sa.String(length=10), nullable=True),
    sa.Column('pending_email_code_expires', sa.DateTime(), nullable=True),
    sa.Column('recovery_email', sa.String(length=120), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('was_enabled', sa.Boolean(), nullable=True),
    sa.Column('blocked_until', sa.DateTime(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=True),
    sa.Column('block_count', sa.Integer(), nullable=True),
    sa.Column('user_session_rev_count', sa.Integer(), nullable=True),
    sa.Column('forgot_token', sa.String(length=100), nullable=True),
    sa.Column('forgot_token_time', sa.DateTime(), nullable=True),
    sa.Column('forgot_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('can_create_subusers', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('saldo_usd', sa.Float(), nullable=True),
    sa.Column('saldo_cop', sa.Float(), nullable=True),
    sa.Column('can_search_any', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('can_access_store', sa.Boolean(), nullable=False),
    sa.Column('can_chat', sa.Boolean(), nullable=False),
    sa.Column('can_manage_subusers', sa.Boolean(), nullable=False),
    sa.Column('is_support', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_forgot_token'), ['forgot_token'], unique=False)

    op.create_table('whatsapp_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('webhook_verify_token', sa.String(length=255), nullable=False),
    sa.Column('template_message', sa.Text(), nullable=False),
    sa.Column('notification_time', sa.Time(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_sent', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worksheet_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('fields', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worksheet_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worksheet_templates_order'), ['order'], unique=False)

    op.create_table('allowed_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'email', name='uq_user_email')
    )
    with op.batch_alter_table('allowed_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allowed_emails_email'), ['email'], unique=False)
        batch_op.create_index('ix_allowed_emails_user_id_email', ['user_id', 'email'], unique=False)

    op.create_table('apiinfo_users',
    sa.Column('apiinfo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['apiinfo_id'], ['api_info.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('apiinfo_id', 'user_id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=10), nullable=False),
    sa.Column('has_attachment', sa.Boolean(), nullable=True),
    sa.Column('attachment_type', sa.String(length=20), nullable=True),
    sa.Column('attachment_filename', sa.String(length=255), nullable=True),
    sa.Column('attachment_path', sa.String(length=500), nullable=True),
    sa.Column('attachment_size', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupon_products',
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['store_coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['store_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coupon_id', 'product_id')
    )
    op.create_table('email_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('filter_from_email', sa.Text(), nullable=True),
    sa.Column('filter_to_email', sa.Text(), nullable=True),
    sa.Column('filter_subject_contains', sa.Text(), nullable=True),
    sa.Column('filter_content_contains', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['email_tags_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('htmlinfo_users',
    sa.Column('htmlinfo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['htmlinfo_id'], ['html_info.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('htmlinfo_id', 'user_id')
    )
    op.create_table('parent_default_filter',
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filter_id'], ['filters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_user_id', 'filter_id')
    )
    with op.batch_alter_table('parent_default_filter', schema=None) as batch_op:
        batch_op.create_index('ix_parent_default_filter_ids', ['parent_user_id', 'filter_id'], unique=False)

    op.create_table('parent_default_regex',
    sa.Column('parent_user_id', sa.Integer(), nullable=False),
    sa.Column('regex_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regex_id'], ['regexes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_user_id', 'regex_id')
    )
    with op.batch_alter_table('parent_default_regex', schema=None) as batch_op:
        batch_op.create_index('ix_parent_default_regex_ids', ['parent_user_id', 'regex_id'], unique=False)

    op.create_table('received_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('buzon_server_id', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buzon_server_id'], ['email_buzon_servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    with op.batch_alter_table('received_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_received_emails_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_received_emails_from_email'), ['from_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_received_emails_processed'), ['processed'], unique=False)
        batch_op.create_index(batch_op.f('ix_received_emails_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_received_emails_to_email'), ['to_email'], unique=False)

    op.create_table('remember_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('role_products',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['store_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['store_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'product_id')
    )
    op.create_table('role_users',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['store_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'user_id')
    )
    op.create_table('security_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('trigger_pattern', sa.Text(), nullable=False),
    sa.Column('observer_pattern', sa.Text(), nullable=False),
    sa.Column('imap_server_id', sa.Integer(), nullable=True),
    sa.Column('imap_folder', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imap_server_id'], ['imap_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('alias_name', sa.String(length=500), nullable=False),
    sa.Column('border_color', sa.String(length=50), nullable=True),
    sa.Column('gradient_color', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_filter',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filter_id'], ['filters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'filter_id')
    )
    op.create_table('service_icons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('icon_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_regex',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('regex_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['regex_id'], ['regexes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'regex_id')
    )
    op.create_table('store_production_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('youtube_listing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['youtube_listing_id'], ['store_youtube_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['store_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('store_sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_sales_created_at'), ['created_at'], unique=False)

    op.create_table('toolinfo_users',
    sa.Column('toolinfo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['toolinfo_id'], ['store_tool_info.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('toolinfo_id', 'user_id')
    )
    op.create_table('user_filter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filter_id'], ['filters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'filter_id')
    )
    op.create_table('user_regex',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('regex_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['regex_id'], ['regexes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'regex_id')
    )
    op.create_table('user_service',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'service_id')
    )
    op.create_table('worksheet_connection_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worksheet_id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('user_identifier', sa.String(length=200), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('connection_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['worksheet_id'], ['worksheet_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worksheet_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('data', sqlite.JSON(), nullable=False),
    sa.Column('formato', sqlite.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_editor', sa.String(length=200), nullable=True),
    sa.Column('last_edit_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['worksheet_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worksheet_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worksheet_id', sa.Integer(), nullable=False),
    sa.Column('access_type', sa.String(length=20), nullable=False),
    sa.Column('public_token', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worksheet_id'], ['worksheet_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_listing_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('youtube_listing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['youtube_listing_id'], ['store_youtube_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'youtube_listing_id')
    )
    op.create_table('alias_icons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_id', sa.Integer(), nullable=False),
    sa.Column('icon_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['alias_id'], ['service_aliases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_tags',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['received_emails.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['email_tags_table.id'], ),
    sa.PrimaryKeyConstraint('email_id', 'tag_id')
    )
    op.create_table('trigger_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('email_identifier', sa.String(length=512), nullable=False),
    sa.Column('searched_email', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['security_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trigger_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trigger_log_email_identifier'), ['email_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_trigger_log_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trigger_log_searched_email'), ['searched_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_trigger_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_trigger_log_user_id'), ['user_id'], unique=False)

    op.create_table('worksheet_permission_users',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['worksheet_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('permission_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worksheet_permission_users')
    with op.batch_alter_table('trigger_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trigger_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_trigger_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_trigger_log_searched_email'))
        batch_op.drop_index(batch_op.f('ix_trigger_log_rule_id'))
        batch_op.drop_index(batch_op.f('ix_trigger_log_email_identifier'))

    op.drop_table('trigger_log')
    op.drop_table('email_tags')
    op.drop_table('alias_icons')
    op.drop_table('youtube_listing_users')
    op.drop_table('worksheet_permissions')
    op.drop_table('worksheet_data')
    op.drop_table('worksheet_connection_logs')
    op.drop_table('user_service')
    op.drop_table('user_regex')
    op.drop_table('user_filter')
    op.drop_table('toolinfo_users')
    with op.batch_alter_table('store_sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_sales_created_at'))

    op.drop_table('store_sales')
    op.drop_table('store_production_links')
    op.drop_table('service_regex')
    op.drop_table('service_icons')
    op.drop_table('service_filter')
    op.drop_table('service_aliases')
    op.drop_table('security_rules')
    op.drop_table('role_users')
    op.drop_table('role_products')
    op.drop_table('remember_devices')
    with op.batch_alter_table('received_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_received_emails_to_email'))
        batch_op.drop_index(batch_op.f('ix_received_emails_received_at'))
        batch_op.drop_index(batch_op.f('ix_received_emails_processed'))
        batch_op.drop_index(batch_op.f('ix_received_emails_from_email'))
        batch_op.drop_index(batch_op.f('ix_received_emails_deleted'))

    op.drop_table('received_emails')
    with op.batch_alter_table('parent_default_regex', schema=None) as batch_op:
        batch_op.drop_index('ix_parent_default_regex_ids')

    op.drop_table('parent_default_regex')
    with op.batch_alter_table('parent_default_filter', schema=None) as batch_op:
        batch_op.drop_index('ix_parent_default_filter_ids')

    op.drop_table('parent_default_filter')
    op.drop_table('htmlinfo_users')
    op.drop_table('email_filters')
    op.drop_table('coupon_products')
    op.drop_table('chat_sessions')
    op.drop_table('chat_messages')
    op.drop_table('apiinfo_users')
    with op.batch_alter_table('allowed_emails', schema=None) as batch_op:
        batch_op.drop_index('ix_allowed_emails_user_id_email')
        batch_op.drop_index(batch_op.f('ix_allowed_emails_email'))

    op.drop_table('allowed_emails')
    with op.batch_alter_table('worksheet_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worksheet_templates_order'))

    op.drop_table('worksheet_templates')
    op.drop_table('whatsapp_configs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_forgot_token'))

    op.drop_table('users')
    op.drop_table('store_youtube_listings')
    with op.batch_alter_table('store_tool_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_tool_info_enabled'))

    op.drop_table('store_tool_info')
    op.drop_table('store_settings')
    with op.batch_alter_table('store_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_roles_enabled'))

    op.drop_table('store_roles')
    with op.batch_alter_table('store_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_products_is_preset'))
        batch_op.drop_index(batch_op.f('ix_store_products_enabled'))

    op.drop_table('store_products')
    with op.batch_alter_table('store_coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_coupons_enabled'))

    op.drop_table('store_coupons')
    op.drop_table('site_settings')
    op.drop_table('services')
    op.drop_table('regexes')
    op.drop_table('observer_imap_servers')
    op.drop_table('imap_servers')
    op.drop_table('html_info')
    with op.batch_alter_table('gsheets_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gsheets_links_plantilla'))

    op.drop_table('gsheets_links')
    op.drop_table('filters')
    op.drop_table('email_tags_table')
    op.drop_table('email_buzon_servers')
    op.drop_table('drive_transfers')
    op.drop_table('domains')
    with op.batch_alter_table('blocked_senders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocked_senders_sender_email'))
        batch_op.drop_index(batch_op.f('ix_blocked_senders_sender_domain'))
        batch_op.drop_index(batch_op.f('ix_blocked_senders_enabled'))

    op.drop_table('blocked_senders')
    op.drop_table('app_secrets')
    op.drop_table('api_info')
    # ### end Alembic commands ###
