"""agregar last_selected_sms_config_id a users

Revision ID: 9ea6e12e9abf
Revises: d9de5c630c4a
Create Date: 2025-11-29 07:23:24.283101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea6e12e9abf'
down_revision = 'd9de5c630c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_selected_sms_config_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sms_configs', ['last_selected_sms_config_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_selected_sms_config_id')

    # ### end Alembic commands ###
