"""Add AllowedSMSNumber table

Revision ID: a0e6c8b16c6a
Revises: 5a3ee0cc817f
Create Date: 2025-11-26 23:55:27.375240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e6c8b16c6a'
down_revision = '5a3ee0cc817f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_sms_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number', name='uq_allowed_sms_number')
    )
    with op.batch_alter_table('allowed_sms_numbers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allowed_sms_numbers_phone_number'), ['phone_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allowed_sms_numbers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allowed_sms_numbers_phone_number'))

    op.drop_table('allowed_sms_numbers')
    # ### end Alembic commands ###
