"""Add TwoFAConfig table

Revision ID: a11d15ef8f0c
Revises: 29b4f76f7dff
Create Date: 2026-01-05 16:57:08.747029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a11d15ef8f0c'
down_revision = '29b4f76f7dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twofa_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret_key', sa.String(length=255), nullable=False),
    sa.Column('emails', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('twofa_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_twofa_configs_is_enabled'), ['is_enabled'], unique=False)

    with op.batch_alter_table('drive_transfers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drive_transfers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('twofa_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_twofa_configs_is_enabled'))

    op.drop_table('twofa_configs')
    # ### end Alembic commands ###
