"""Agregar modelos de licencias

Revision ID: ac9bfea3ff09
Revises: 8be184b55cc2
Create Date: 2025-10-24 16:29:05.117061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9bfea3ff09'
down_revision = '8be184b55cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['store_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('store_licenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_licenses_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_licenses_position'), ['position'], unique=False)

    op.create_table('store_license_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Integer(), nullable=False),
    sa.Column('account_identifier', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['license_id'], ['store_licenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_buzon_servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smtp_port', sa.Integer(), nullable=True))
        batch_op.drop_column('webhook_port')

    with op.batch_alter_table('email_forwarding', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('ix_email_forwarding_source_email'))
        batch_op.create_index(batch_op.f('ix_email_forwarding_source_email'), ['source_email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_forwarding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_forwarding_source_email'))
        batch_op.create_index(batch_op.f('ix_email_forwarding_source_email'), ['source_email'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('email_buzon_servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhook_port', sa.INTEGER(), nullable=True))
        batch_op.drop_column('smtp_port')

    op.drop_table('store_license_accounts')
    with op.batch_alter_table('store_licenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_licenses_position'))
        batch_op.drop_index(batch_op.f('ix_store_licenses_enabled'))

    op.drop_table('store_licenses')
    # ### end Alembic commands ###
