"""agregar_campo_can_manage_own_emails

Revision ID: b6dffb52816f
Revises: a11d15ef8f0c
Create Date: 2026-01-06 04:37:37.830315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6dffb52816f'
down_revision = 'a11d15ef8f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_add_own_emails', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_add_own_emails')
    # ### end Alembic commands ###
