"""agregar campo number_type a sms_configs para almacenar tipo de numero twilio

Revision ID: bb6bd174a633
Revises: cb450fbd3283
Create Date: 2025-11-29 17:57:58.853837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6bd174a633'
down_revision = 'cb450fbd3283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite no permite agregar una columna NOT NULL sin valor por defecto
    # Agregamos la columna como nullable primero
    with op.batch_alter_table('sms_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_type', sa.String(length=20), nullable=True))
    
    # Actualizar todas las filas existentes con el valor por defecto
    op.execute("UPDATE sms_configs SET number_type = 'desconocido' WHERE number_type IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_configs', schema=None) as batch_op:
        batch_op.drop_column('number_type')

    # ### end Alembic commands ###
