"""agregar tabla sms_config_regex para asociar regex con sms configs

Revision ID: ef7bda1b1e3c
Revises: 9ea6e12e9abf
Create Date: 2025-11-29 08:25:26.443192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7bda1b1e3c'
down_revision = '9ea6e12e9abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_config_regex',
    sa.Column('sms_config_id', sa.Integer(), nullable=False),
    sa.Column('regex_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['regex_id'], ['regexes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sms_config_id'], ['sms_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sms_config_id', 'regex_id')
    )
    with op.batch_alter_table('sms_config_regex', schema=None) as batch_op:
        batch_op.create_index('ix_sms_config_regex_ids', ['sms_config_id', 'regex_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms_config_regex', schema=None) as batch_op:
        batch_op.drop_index('ix_sms_config_regex_ids')

    op.drop_table('sms_config_regex')
    # ### end Alembic commands ###
